title: 最新iptv直播源播放列表
description: GitHub自动程序生成的最新可用的iptv直播源播放列表
show_downloads: false
url: https://live.zbds.top
google_analytics: # 如果有 Google Analytics 代码，请添加到这里
theme: jekyll-theme-cayman
#remote_theme: pages-themes/cayman@v0.2.0
encoding: "utf-8"

collections:
  pages:
    output: true
    permalink: /:path/

